/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cn.devit.demo.planner
dialect "java"

import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScoreHolder;

import cn.devit.rectangle.Visit;
import java.awt.Point;

global HardSoftScoreHolder scoreHolder;


rule "周长最短"
    when
        
        $visit:Visit( prevPoint != null, $distance :distance)
    then
        scoreHolder.addSoftConstraintMatch(kcontext, -(int)($distance*10));
end
/*
rule "不能是自己"
    when
        
        //$point : Point()
        $visit:Visit( prevPoint == $visit)
    then
        scoreHolder.addHardConstraintMatch(kcontext, - 1);
end*/

/*rule "非空"
    when
        
        $home : Point()
        $visit:Visit(prevPoint == null, point  != $home)
    then
        scoreHolder.addHardConstraintMatch(kcontext, - 1);
end*/

